behaviors:
  GuardBehavior:
    trainer_type: poca
    hyperparameters:
      batch_size: 16000
      buffer_size: 128000
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: trues
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.998
        strength: 1.0
      curiosity:
        gamma: 0.998
        strength: 0.05
        network_settings:
          normalize: true
          hidden_units: 256
        learning_rate: 0.0001
    threaded: true
    keep_checkpoints: 100
    checkpoint_interval: 10000000
    max_steps: 2000000000
    time_horizon: 256
    summary_freq: 30000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 1000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
  ThiefBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16000
      buffer_size: 768000
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.998
        strength: 1.0
      curiosity:
        gamma: 0.998
        strength: 0.05
        network_settings:
          normalize: true
          hidden_units: 256
        learning_rate: 0.0001
    threaded: true
    keep_checkpoints: 100
    checkpoint_interval: 10000000
    max_steps: 2000000000
    time_horizon: 256
    summary_freq: 30000
    # self_play:
    #   save_steps: 50000
    #   team_change: 200000
    #   swap_steps: 1000
    #   window: 10
    #   play_against_latest_model_ratio: 0.5
    #   initial_elo: 1200.0